# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7eb64c887117079e2f2ff7b87c9fc936c07b7e82ae1eaba32a6c5bb4203d4fa249d3315f91093cc771d442ed1e6848bffe0c3053d82205d64120758bce86153

test:
  secret_key_base: d809a373019458c2e6d049946937227e36dba8f69013bcba26bbced8d2a92ee8b169e31293f13c7f094221f8cdd183849a2b89a7d83a8bec50fc382346a39d46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
